# Generated by Django 5.0.1 on 2025-12-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('priority', models.IntegerField(choices=[(1, 'P1'), (2, 'P2'), (3, 'P3')], default=2)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('rail', 'Rail'), ('road', 'Road')], default='rail', max_length=10)),
                ('dest_code', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('automated', 'Automated'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['priority', 'deadline'],
                'indexes': [models.Index(fields=['priority', 'deadline'], name='idx_order_priority_deadline'), models.Index(fields=['mode', 'dest_code'], name='idx_order_mode_dest'), models.Index(fields=['status'], name='idx_order_status')],
            },
        ),
        migrations.CreateModel(
            name='Stockyard',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stockyards',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['material'], name='idx_stockyard_material')],
            },
        ),
    ]
